name: SX-Menu
main: github.saukiya.sxmenu.SXMenu
version: $version
author: Saukiya
api-version: 1.17

depend:
- PlaceholderAPI

softdepend:
- Vault

commands:
  sxmenu:
    aliases: [sm]

permissions:
  sx-menu.use:
    default: true
